Header header

Status status

Status c2_status
Status comms_status
Status corr_status
Status lidar_status
Status ss1_status
Status ss2_status
Status vislog_status

int8 cpu_percent_total
int8[] cpu_percent_cores

uint32 memory_phys_total_kb
uint32 memory_phys_used_kb
uint32 memory_swap_total_kb
uint32 memory_swap_used_kb

uint32 wifi_sent_total_kb
uint32 wifi_received_total_kb
uint32 wifi_sent_bps
uint32 wifi_received_bps
