#a service to activate multiple cameras
#choose from the list below only.
#front_left
#front_right
#down_front
#down_back
#fpv
#main
#send an empty message to turn all the cameras off
string[] cameras

---
bool result
