name: Release Candidate
on: 
  push:
    branches-ignore:
      - master
jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [[x64, self-hosted,linux,build], [arm64,self-hosted,linux, build]]
      fail-fast: false
    steps:
      - uses: AutoModality/action-clean@v1.1.0
      - uses: actions/checkout@v2
      - name: Deploy
        run: amros dev docker run -dm --command="deploy-amros ${{ secrets.DEVELOPER_PASSWORD }} 0.0.${{ github.run_number }} dev ${{ secrets.CLOUDSMITH_API_KEY }}"
  draft-pr:
    runs-on: ubuntu-18.04
    needs: package
    steps:
      - uses: actions/checkout@v2
      - name: Draft a Pull Request
        uses: repo-sync/pull-request@v2
        with:
          pr_draft: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
