name: Release Candidate
on: 
  push:
    branches-ignore:
      - master 
jobs:
  package:
    runs-on: [x64, self-hosted,linux,build]
    steps:
      - uses: AutoModality/action-clean@v1.1.0
      - uses: actions/checkout@v2
      - uses: rlespinasse/github-slug-action@3.1.0
      - name: Deploy
        id: deploy
        run: amros dev docker run -dm --command="deploy-amros ${{ secrets.DEVELOPER_PASSWORD }} ${{ github.run_number }}-${{ env.GITHUB_REF_SLUG }} dev ${{ secrets.CLOUDSMITH_API_KEY }}"
  package-arm:
    runs-on: [arm64,self-hosted,linux, cuda]
    steps:
      - uses: AutoModality/action-clean@v1.1.0
      - uses: actions/checkout@v2
      - uses: rlespinasse/github-slug-action@3.1.0
      - name: Deploy
        id: deploy
        run: deploy-amros ${{ secrets.DEVELOPER_PASSWORD }} ${{ github.run_number }}-${{ env.GITHUB_REF_SLUG }} dev ${{ secrets.CLOUDSMITH_API_KEY }}
  draft-pr:
    runs-on: ubuntu-18.04
    needs: 
      - package
      - package-arm
    steps:
      - uses: actions/checkout@v2
      - name: Draft a Pull Request
        uses: repo-sync/pull-request@v2
        with:
          pr_draft: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

