name: Release Candidate
on: 
  push:
    branches-ignore:
      - master
jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [[x64, self-hosted,linux,build], [arm64,self-hosted,linux, build]]
      fail-fast: false
    steps:
      - uses: AutoModality/action-clean@v1.1.0
      - uses: actions/checkout@v2
      - uses: rlespinasse/github-slug-action@3.1.0 # for GITHUB_REF_SLUG
      - name: Package
        id: package
        uses: AutoModality/action-package-debian-ros@v5-amros
        with:
          branch: ${{ env.GITHUB_REF_SLUG }}
          build-number: ${{ github.run_number }}
          release-repo-entitlement: ${{ secrets.CLOUDSMITH_READ_RELEASE_ENTITLEMENT }}
      - name: The generated package
        run: echo "The artifact is ${{ steps.package.outputs.artifact-path }}"
      - name: Deploy
        id: deploy
        uses: AutoModality/action-cloudsmith@0.2.0
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: 'push'
          format: 'deb'
          owner: 'automodality'
          repo: 'dev'
          distro: 'ubuntu'
          release: 'bionic'
          file: '${{ steps.package.outputs.artifact-path }}'
  merge-pr:
    name: Success. Merge to master
    runs-on: ubuntu-18.04
    needs: package
    steps:
      - uses: actions/checkout@v2
      - name: Create a Pull Request
        uses: repo-sync/pull-request@v2
        with:
          pr_draft: false
          github_token: ${{ secrets.AMGITBOT_PAT }}
      - name: Merge PR to master
        uses: ridedott/merge-me-action@master
        with:
          GITHUB_LOGIN: amgitbot
          GITHUB_TOKEN: ${{ secrets.AMGITBOT_PAT }}
          MERGE_METHOD: MERGE
