name: Updated Pull Requests

on:
    push:
        branches: 
            - master

jobs:
    autoupdate:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: update all pull requests
          uses: maxkomarychev/pr-updater-action@v1.0.0
          with:
              token: ${{ secrets.USER_TOKEN }}